[package]
name = "opentelemetry-stackdriver"
version = "0.1.0"
authors = ["jacobkiesel <jacob.kiesel@vivint.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
protoc-grpcio = "1.1" 

[dependencies]
derivative = "1.0"
grpcio = { version = "0.4", features = ["openssl"] }
log = "0.4"
opentelemetry = "0.2"
num_cpus = "1.12"
protobuf = "2.0"
