[package]
name = "opentelemetry-stackdriver"
version = "0.2.0"
description = "A Rust opentelemetry exporter that uploads traces to Google Stackdriver trace."
documentation = "https://vivint-smarthome.github.io/opentelemetry-stackdriver/opentelemetry_stackdriver/"
repository = "https://github.com/vivint-smarthome/opentelemetry-stackdriver"
license = "MIT/Apache-2.0"
authors = ["jacobkiesel <jacob.kiesel@vivint.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
protoc-grpcio = "1.1" 

[dependencies]
derivative = "1.0"
futures = "0.1"
grpcio = { version = "0.4", features = ["openssl"] }
hex = "0.4"
log = "0.4"
num_cpus = "1.12"
opentelemetry = "0.2"
protobuf = "2.0"
tokio = "0.1"
