[package]
name = "opentelemetry-stackdriver"
version = "0.1.0"
authors = ["jacobkiesel <jacob.kiesel@vivint.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
protoc-rust-grpc = "0.6" 

[dependencies]
grpc = "0.6"
protobuf = "2.0"
opentelemetry = "0.2"
